graph TD
    A[House prediction model] -->|Data Set| B(Train Data set)
    B --> C{Test Data set}
    C -->|One| D["Build Model<br> Linear Regression"]
    C -->|Two| E[Deploy Model]
    C -->|Three| F[Test Model]
